production:
  solr:
    hostname: <%= Rails.application.credentials.dig(:solr, :hostname) %>
    port: <%= Rails.application.credentials.dig(:solr, :port) %>
    log_level: <%= Rails.application.credentials.dig(:solr, :log_level) %>
    path: <%= Rails.application.credentials.dig(:solr, :path) %>
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: <%= Rails.application.credentials.dig(:solr, :hostname) %>
    port: <%= Rails.application.credentials.dig(:solr, :port) %>
    log_level: <%= Rails.application.credentials.dig(:solr, :log_level) %>
    path: <%= Rails.application.credentials.dig(:solr, :path) %>

test:
  solr:
    hostname: <%= Rails.application.credentials.dig(:solr, :hostname) %>
    port: <%= Rails.application.credentials.dig(:solr, :port) %>
    log_level: <%= Rails.application.credentials.dig(:solr, :log_level) %>
    path: <%= Rails.application.credentials.dig(:solr, :path) %>
    